packages:
  - "v17"
  - "v18"

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
allowBuilds:
  esbuild: true
  unrs-resolver: true
blockExoticSubdeps: true
overrides:
  "@umbraco-ui/uui": "2.0.1"
  dompurify@<=3.4.12: ^3.4.13
  uuid: "14.0.1"
  js-yaml@<4.3.1: ^4.3.1
  brace-expansion@<=5.0.8: ^5.0.9
  nanoid@<3.3.17: ^3.3.17
  postcss@<=8.5.22: ^8.5.23
minimumReleaseAgeExclude:
  - dompurify@3.4.13
  - postcss@8.5.23
  - brace-expansion@5.0.9
  - js-yaml@4.3.1
  - nanoid@3.3.17
