packages:
  - "v17"
  - "v18"

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
allowBuilds:
  esbuild: true
  unrs-resolver: true
blockExoticSubdeps: true
overrides:
  "@umbraco-ui/uui": "2.0.1"
  dompurify@<=3.4.11: ^3.4.12
  uuid: "14.0.1"
  js-yaml@>=4.0.0 <4.3.0: ^4.3.0
  brace-expansion@<=5.0.7: ^5.0.8
minimumReleaseAgeExclude:
  - js-yaml@4.3.0
  - dompurify@3.4.12
  - brace-expansion@5.0.8
