// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { GetAuthenticationCsrfTokenData, GetAuthenticationCsrfTokenResponses, PostAuthenticationLoginData, PostAuthenticationLoginResponses, PostAuthenticationLoginErrors, PostAuthenticationLogoutData, PostAuthenticationLogoutResponses, PostAuthenticationLogoutErrors, GetAuthenticationStatusData, GetAuthenticationStatusResponses, GetAuthenticationStatusErrors, PostArticulateBlogmlExportData, PostArticulateBlogmlExportResponses, PostArticulateBlogmlExportErrors, GetArticulateBlogmlExportDisqusData, GetArticulateBlogmlExportDisqusResponses, GetArticulateBlogmlExportDisqusErrors, PostArticulateBlogmlImportData, PostArticulateBlogmlImportResponses, PostArticulateBlogmlImportErrors, PostArticulateBlogmlImportFileData, PostArticulateBlogmlImportFileResponses, PostArticulateBlogmlImportFileErrors, PostArticulateEditorsMarkdownPostData, PostArticulateEditorsMarkdownPostResponses, PostArticulateEditorsMarkdownPostErrors, GetArticulateEditorsThemePickerThemesData, GetArticulateEditorsThemePickerThemesResponses, GetArticulateEditorsThemePickerThemesErrors, PostArticulateThemesCopyData, PostArticulateThemesCopyResponses, PostArticulateThemesCopyErrors, GetArticulateThemesDefaultData, GetArticulateThemesDefaultResponses, GetArticulateThemesDefaultErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Authentication {
    /**
     * Gets a CSRF token required for authenticated POST/PUT requests.
     */
    public static getAuthenticationCsrfToken<ThrowOnError extends boolean = false>(options?: Options<GetAuthenticationCsrfTokenData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAuthenticationCsrfTokenResponses, unknown, ThrowOnError>({
            url: '/articulate/management/api/v1/authentication/csrf-token',
            ...options
        });
    }
    
    /**
     * Authenticates a user with the provided credentials.
     */
    public static postAuthenticationLogin<ThrowOnError extends boolean = false>(options?: Options<PostAuthenticationLoginData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostAuthenticationLoginResponses, PostAuthenticationLoginErrors, ThrowOnError>({
            url: '/articulate/management/api/v1/authentication/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Logs out the currently authenticated user.
     * Signs out the current user and ends their session.
     */
    public static postAuthenticationLogout<ThrowOnError extends boolean = false>(options?: Options<PostAuthenticationLogoutData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostAuthenticationLogoutResponses, PostAuthenticationLogoutErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/articulate/management/api/v1/authentication/logout',
            ...options
        });
    }
    
    /**
     * Gets the authentication status of the current user.
     */
    public static getAuthenticationStatus<ThrowOnError extends boolean = false>(options?: Options<GetAuthenticationStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAuthenticationStatusResponses, GetAuthenticationStatusErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/articulate/management/api/v1/authentication/status',
            ...options
        });
    }
}

export class BlogMl {
    /**
     * Exports blog data as a BlogML XML file.
     */
    public static postArticulateBlogmlExport<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlExportData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlExportResponses, PostArticulateBlogmlExportErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/export',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Downloads the exported Disqus comment XML file.
     */
    public static getArticulateBlogmlExportDisqus<ThrowOnError extends boolean = false>(options?: Options<GetArticulateBlogmlExportDisqusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateBlogmlExportDisqusResponses, GetArticulateBlogmlExportDisqusErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/export/disqus',
            ...options
        });
    }
    
    /**
     * Imports blog data from a previously uploaded BlogML XML file.
     */
    public static postArticulateBlogmlImport<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlImportData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlImportResponses, PostArticulateBlogmlImportErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/import',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Begins the BlogML import process by accepting an uploaded XML file.
     * The name specified in the form's element or FormData must match the name of the parameter, e.g., <input type="file" name="importFile">
     */
    public static postArticulateBlogmlImportFile<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlImportFileData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlImportFileResponses, PostArticulateBlogmlImportFileErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/import-file',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}

export class MarkdownEditor {
    public static postArticulateEditorsMarkdownPost<ThrowOnError extends boolean = false>(options?: Options<PostArticulateEditorsMarkdownPostData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateEditorsMarkdownPostResponses, PostArticulateEditorsMarkdownPostErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/editors/markdown/post',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}

export class ThemePicker {
    /**
     * Gets the list of all available Articulate themes, both default and user-defined.
     * This endpoint returns the names of all available themes, including both default and user-defined themes.
     */
    public static getArticulateEditorsThemePickerThemes<ThrowOnError extends boolean = false>(options?: Options<GetArticulateEditorsThemePickerThemesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateEditorsThemePickerThemesResponses, GetArticulateEditorsThemePickerThemesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/editors/theme-picker/themes',
            ...options
        });
    }
}

export class Themes {
    public static postArticulateThemesCopy<ThrowOnError extends boolean = false>(options?: Options<PostArticulateThemesCopyData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateThemesCopyResponses, PostArticulateThemesCopyErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/themes/copy',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getArticulateThemesDefault<ThrowOnError extends boolean = false>(options?: Options<GetArticulateThemesDefaultData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateThemesDefaultResponses, GetArticulateThemesDefaultErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/themes/default',
            ...options
        });
    }
}