// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { GetAuthenticationCsrfTokenData, GetAuthenticationCsrfTokenResponses, PostAuthenticationLoginData, PostAuthenticationLoginResponses, PostAuthenticationLoginErrors, PostAuthenticationLogoutData, PostAuthenticationLogoutResponses, PostAuthenticationLogoutErrors, GetAuthenticationStatusData, GetAuthenticationStatusResponses, GetAuthenticationStatusErrors, PostArticulatePostsMarkdownData, PostArticulatePostsMarkdownResponses, PostArticulatePostsMarkdownErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Authentication {
    /**
     * Gets a CSRF token for the current session.
     */
    public static getAuthenticationCsrfToken<ThrowOnError extends boolean = false>(options?: Options<GetAuthenticationCsrfTokenData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAuthenticationCsrfTokenResponses, unknown, ThrowOnError>({
            url: '/articulate/management/api/v1/authentication/csrf-token',
            ...options
        });
    }
    
    /**
     * Authenticates a user with the provided credentials.
     */
    public static postAuthenticationLogin<ThrowOnError extends boolean = false>(options?: Options<PostAuthenticationLoginData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostAuthenticationLoginResponses, PostAuthenticationLoginErrors, ThrowOnError>({
            url: '/articulate/management/api/v1/authentication/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Logs out the currently authenticated user.
     * Signs out the current user and ends their session.
     */
    public static postAuthenticationLogout<ThrowOnError extends boolean = false>(options?: Options<PostAuthenticationLogoutData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostAuthenticationLogoutResponses, PostAuthenticationLogoutErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/articulate/management/api/v1/authentication/logout',
            ...options
        });
    }
    
    /**
     * Gets the authentication status of the current user.
     */
    public static getAuthenticationStatus<ThrowOnError extends boolean = false>(options?: Options<GetAuthenticationStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAuthenticationStatusResponses, GetAuthenticationStatusErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/articulate/management/api/v1/authentication/status',
            ...options
        });
    }
}

export class Posts {
    public static postArticulatePostsMarkdown<ThrowOnError extends boolean = false>(options?: Options<PostArticulatePostsMarkdownData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulatePostsMarkdownResponses, PostArticulatePostsMarkdownErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/posts/markdown',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}