// This file is auto-generated by @hey-api/openapi-ts

/**
 * Represents the response when two-factor authentication is required.
 */
export type TwoFactorRequiredResponse = {
    /**
     * Gets a value indicating whether two-factor authentication is required.
     */
    requiresTwoFactor: boolean;
    /**
     * Gets the URL to redirect the user for two-factor authentication.
     */
    redirectUrl?: string | null;
};

/**
 * Represents the authentication status response.
 */
export type StatusResponse = {
    /**
     * Gets a value indicating whether the user is authenticated.
     */
    isAuthenticated: boolean;
};

/**
 * Represents the login model for authentication.
 */
export type LoginModel = {
    /**
     * Gets the email address of the user.
     */
    readonly emailAddress: string;
    /**
     * Gets the password of the user.
     */
    readonly password: string;
};

/**
 * Represents the CSRF token response.
 */
export type CsrfTokenResponse = {
    /**
     * Gets the CSRF request token.
     */
    requestToken?: string | null;
};

export type GetAuthenticationCsrfTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/csrf-token';
};

export type GetAuthenticationCsrfTokenResponses = {
    /**
     * Represents the CSRF token response.
     */
    200: CsrfTokenResponse;
};

export type GetAuthenticationCsrfTokenResponse = GetAuthenticationCsrfTokenResponses[keyof GetAuthenticationCsrfTokenResponses];

export type PostAuthenticationLoginData = {
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/login';
};

export type PostAuthenticationLoginErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Locked
     */
    423: unknown;
};

export type PostAuthenticationLoginResponses = {
    /**
     * Represents the response when two-factor authentication is required.
     */
    200: TwoFactorRequiredResponse;
};

export type PostAuthenticationLoginResponse = PostAuthenticationLoginResponses[keyof PostAuthenticationLoginResponses];

export type PostAuthenticationLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/logout';
};

export type PostAuthenticationLogoutErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostAuthenticationLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAuthenticationStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/status';
};

export type GetAuthenticationStatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAuthenticationStatusResponses = {
    /**
     * Represents the authentication status response.
     */
    200: StatusResponse;
};

export type GetAuthenticationStatusResponse = GetAuthenticationStatusResponses[keyof GetAuthenticationStatusResponses];

export type PostArticulatePostsMarkdownData = {
    body?: {
        json?: string;
        files?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/posts/markdown';
};

export type PostArticulatePostsMarkdownErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostArticulatePostsMarkdownResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:44366' | (string & {});
};