// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetServerConfigurationData, GetServerConfigurationResponses, GetServerInformationData, GetServerInformationResponses, GetServerInformationErrors, GetServerStatusData, GetServerStatusResponses, GetServerStatusErrors, GetServerTroubleshootingData, GetServerTroubleshootingResponses, GetServerTroubleshootingErrors, GetServerUpgradeCheckData, GetServerUpgradeCheckResponses, GetServerUpgradeCheckErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Server {
    public static getServerConfiguration<ThrowOnError extends boolean = false>(options?: Options<GetServerConfigurationData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetServerConfigurationResponses, unknown, ThrowOnError>({
            url: '/umbraco/management/api/v1/server/configuration',
            ...options
        });
    }
    
    public static getServerInformation<ThrowOnError extends boolean = false>(options?: Options<GetServerInformationData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetServerInformationResponses, GetServerInformationErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/server/information',
            ...options
        });
    }
    
    public static getServerStatus<ThrowOnError extends boolean = false>(options?: Options<GetServerStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetServerStatusResponses, GetServerStatusErrors, ThrowOnError>({
            url: '/umbraco/management/api/v1/server/status',
            ...options
        });
    }
    
    public static getServerTroubleshooting<ThrowOnError extends boolean = false>(options?: Options<GetServerTroubleshootingData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetServerTroubleshootingResponses, GetServerTroubleshootingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/server/troubleshooting',
            ...options
        });
    }
    
    public static getServerUpgradeCheck<ThrowOnError extends boolean = false>(options?: Options<GetServerUpgradeCheckData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetServerUpgradeCheckResponses, GetServerUpgradeCheckErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/server/upgrade-check',
            ...options
        });
    }
}