// This file is auto-generated by @hey-api/openapi-ts

export type UpgradeCheckResponseModel = {
    type: string;
    comment: string;
    url: string;
};

export type ServerTroubleshootingResponseModel = {
    items: Array<ServerConfigurationItemResponseModel>;
};

export type ServerConfigurationItemResponseModel = {
    name: string;
    data: string;
};

export type ServerStatusResponseModel = {
    serverStatus: RuntimeLevelModel;
};

export enum RuntimeLevelModel {
    UNKNOWN = 'Unknown',
    BOOT = 'Boot',
    INSTALL = 'Install',
    UPGRADE = 'Upgrade',
    RUN = 'Run',
    BOOT_FAILED = 'BootFailed'
}

export type ServerInformationResponseModel = {
    version: string;
    assemblyVersion: string;
    baseUtcOffset: string;
    runtimeMode: RuntimeModeModel;
};

export enum RuntimeModeModel {
    BACKOFFICE_DEVELOPMENT = 'BackofficeDevelopment',
    DEVELOPMENT = 'Development',
    PRODUCTION = 'Production'
}

export type ServerConfigurationResponseModel = {
    allowPasswordReset: boolean;
    versionCheckPeriod: number;
    allowLocalLogin: boolean;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type GetServerConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/configuration';
};

export type GetServerConfigurationResponses = {
    /**
     * OK
     */
    200: ServerConfigurationResponseModel;
};

export type GetServerConfigurationResponse = GetServerConfigurationResponses[keyof GetServerConfigurationResponses];

export type GetServerInformationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/information';
};

export type GetServerInformationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetServerInformationResponses = {
    /**
     * OK
     */
    200: ServerInformationResponseModel;
};

export type GetServerInformationResponse = GetServerInformationResponses[keyof GetServerInformationResponses];

export type GetServerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/status';
};

export type GetServerStatusErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetServerStatusError = GetServerStatusErrors[keyof GetServerStatusErrors];

export type GetServerStatusResponses = {
    /**
     * OK
     */
    200: ServerStatusResponseModel;
};

export type GetServerStatusResponse = GetServerStatusResponses[keyof GetServerStatusResponses];

export type GetServerTroubleshootingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/troubleshooting';
};

export type GetServerTroubleshootingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetServerTroubleshootingResponses = {
    /**
     * OK
     */
    200: ServerTroubleshootingResponseModel;
};

export type GetServerTroubleshootingResponse = GetServerTroubleshootingResponses[keyof GetServerTroubleshootingResponses];

export type GetServerUpgradeCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/upgrade-check';
};

export type GetServerUpgradeCheckErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetServerUpgradeCheckResponses = {
    /**
     * OK
     */
    200: UpgradeCheckResponseModel;
};

export type GetServerUpgradeCheckResponse = GetServerUpgradeCheckResponses[keyof GetServerUpgradeCheckResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44366' | (string & {});
};