// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { GetArticulateBlogArticulateGuidV1Data, GetArticulateBlogArticulateGuidV1Responses, GetArticulateBlogArticulateGuidV1Errors, PostArticulateBlogExportV1Data, PostArticulateBlogExportV1Responses, PostArticulateBlogExportV1Errors, GetArticulateBlogExportDisqusV1Data, GetArticulateBlogExportDisqusV1Responses, GetArticulateBlogExportDisqusV1Errors, PostArticulateBlogImportV1Data, PostArticulateBlogImportV1Responses, PostArticulateBlogImportV1Errors, PostArticulateBlogImportBeginV1Data, PostArticulateBlogImportBeginV1Responses, PostArticulateBlogImportBeginV1Errors, GetArticulateEditorsThemesV1Data, GetArticulateEditorsThemesV1Responses, GetArticulateEditorsThemesV1Errors, PostArticulateThemesCopyV1Data, PostArticulateThemesCopyV1Responses, PostArticulateThemesCopyV1Errors, GetArticulateThemesDefaultV1Data, GetArticulateThemesDefaultV1Responses, GetArticulateThemesDefaultV1Errors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Articulate {
    /**
     * Gets the Guid for the Articulate content type.
     * This endpoint is used to retrieve the Guid for the back office import and export features.
     */
    public static getArticulateBlogArticulateGuidV1<ThrowOnError extends boolean = false>(options?: Options<GetArticulateBlogArticulateGuidV1Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateBlogArticulateGuidV1Responses, GetArticulateBlogArticulateGuidV1Errors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blog/articulate/guid',
            ...options
        });
    }
    
    /**
     * Exports blog data as a BlogML XML file.
     */
    public static postArticulateBlogExportV1<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogExportV1Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogExportV1Responses, PostArticulateBlogExportV1Errors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blog/export',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Downloads the exported Disqus comment XML file, if one was generated by the BlogML import.
     * This endpoint should be called after importing the BlogML file with the articulate/blog/import endpoint.
     */
    public static getArticulateBlogExportDisqusV1<ThrowOnError extends boolean = false>(options?: Options<GetArticulateBlogExportDisqusV1Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateBlogExportDisqusV1Responses, GetArticulateBlogExportDisqusV1Errors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blog/export/disqus',
            ...options
        });
    }
    
    /**
     * Imports blog data from a previously uploaded BlogML XML file.
     * This endpoint should be called after initializing the import with the articulate/blog/import/begin endpoint.
     */
    public static postArticulateBlogImportV1<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogImportV1Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogImportV1Responses, PostArticulateBlogImportV1Errors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blog/import',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Begins the BlogML import process by accepting an uploaded XML file, storing it temporarily, and returning a temporary file name along with the detected post count.
     * This endpoint must be called before performing a blog export using the articulate/blog/import endpoint.
     * The name specified in the form's element or FormData must match the name of the parameter in the controller's action, e.g. &lt;input type="file" name="importFile"&gt;
     */
    public static postArticulateBlogImportBeginV1<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogImportBeginV1Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogImportBeginV1Responses, PostArticulateBlogImportBeginV1Errors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blog/import/begin',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
    
    /**
     * Gets the list of all available Articulate themes, both default and user-defined.
     * This endpoint returns the names of all available themes, including both default and user-defined themes.
     */
    public static getArticulateEditorsThemesV1<ThrowOnError extends boolean = false>(options?: Options<GetArticulateEditorsThemesV1Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateEditorsThemesV1Responses, GetArticulateEditorsThemesV1Errors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/editors/themes',
            ...options
        });
    }
    
    /**
     * Copies an existing theme to a new theme with a specified name.
     * This endpoint creates a copy of an existing theme under a new name. The new theme name must be unique.
     */
    public static postArticulateThemesCopyV1<ThrowOnError extends boolean = false>(options?: Options<PostArticulateThemesCopyV1Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateThemesCopyV1Responses, PostArticulateThemesCopyV1Errors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/themes/copy',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Retrieves the list of available default Articulate themes.
     * This endpoint returns the names of default themes available for Articulate.
     */
    public static getArticulateThemesDefaultV1<ThrowOnError extends boolean = false>(options?: Options<GetArticulateThemesDefaultV1Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateThemesDefaultV1Responses, GetArticulateThemesDefaultV1Errors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/themes/default',
            ...options
        });
    }
}