// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { GetAuthenticationCsrfTokenData, GetAuthenticationCsrfTokenResponses, PostAuthenticationLoginData, PostAuthenticationLoginResponses, PostAuthenticationLoginErrors, PostAuthenticationLogoutData, PostAuthenticationLogoutResponses, PostAuthenticationLogoutErrors, GetAuthenticationStatusData, GetAuthenticationStatusResponses, GetAuthenticationStatusErrors, PostArticulateBlogmlExportData, PostArticulateBlogmlExportResponses, PostArticulateBlogmlExportErrors, GetArticulateBlogmlExportDisqusData, GetArticulateBlogmlExportDisqusResponses, GetArticulateBlogmlExportDisqusErrors, PostArticulateBlogmlImportData, PostArticulateBlogmlImportResponses, PostArticulateBlogmlImportErrors, PostArticulateBlogmlImportFileData, PostArticulateBlogmlImportFileResponses, PostArticulateBlogmlImportFileErrors, PostArticulatePostsMarkdownData, PostArticulatePostsMarkdownResponses, PostArticulatePostsMarkdownErrors, GetArticulateThemesAllData, GetArticulateThemesAllResponses, GetArticulateThemesAllErrors, PostArticulateThemesCopyData, PostArticulateThemesCopyResponses, PostArticulateThemesCopyErrors, GetArticulateThemesDefaultData, GetArticulateThemesDefaultResponses, GetArticulateThemesDefaultErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Authentication {
    /**
     * Gets a CSRF token for the current session.
     */
    public static getAuthenticationCsrfToken<ThrowOnError extends boolean = false>(options?: Options<GetAuthenticationCsrfTokenData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAuthenticationCsrfTokenResponses, unknown, ThrowOnError>({
            url: '/articulate/management/api/v1/authentication/csrf-token',
            ...options
        });
    }
    
    /**
     * Authenticates a user with the provided credentials.
     */
    public static postAuthenticationLogin<ThrowOnError extends boolean = false>(options?: Options<PostAuthenticationLoginData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostAuthenticationLoginResponses, PostAuthenticationLoginErrors, ThrowOnError>({
            url: '/articulate/management/api/v1/authentication/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Logs out the currently authenticated user.
     * Signs out the current user and ends their session.
     */
    public static postAuthenticationLogout<ThrowOnError extends boolean = false>(options?: Options<PostAuthenticationLogoutData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostAuthenticationLogoutResponses, PostAuthenticationLogoutErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/articulate/management/api/v1/authentication/logout',
            ...options
        });
    }
    
    /**
     * Gets the authentication status of the current user.
     */
    public static getAuthenticationStatus<ThrowOnError extends boolean = false>(options?: Options<GetAuthenticationStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAuthenticationStatusResponses, GetAuthenticationStatusErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/articulate/management/api/v1/authentication/status',
            ...options
        });
    }
}

export class BlogMl {
    /**
     * Exports blog data as a BlogML XML file.
     */
    public static postArticulateBlogmlExport<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlExportData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlExportResponses, PostArticulateBlogmlExportErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/export',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Downloads the exported Disqus comment XML file, if one was generated by the BlogML import.
     * This endpoint should be called after importing the BlogML file with the articulate/blog/import endpoint.
     */
    public static getArticulateBlogmlExportDisqus<ThrowOnError extends boolean = false>(options?: Options<GetArticulateBlogmlExportDisqusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateBlogmlExportDisqusResponses, GetArticulateBlogmlExportDisqusErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/export/disqus',
            ...options
        });
    }
    
    /**
     * Imports blog data from a previously uploaded BlogML XML file.
     * This endpoint should be called after initializing the import with the articulate/blog/import/begin endpoint.
     */
    public static postArticulateBlogmlImport<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlImportData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlImportResponses, PostArticulateBlogmlImportErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/import',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Begins the BlogML import process by accepting an uploaded XML file, storing it temporarily, and returning a temporary file name along with the detected post count.
     * This endpoint must be called before performing a blog export using the articulate/blog/import endpoint.
     * The name specified in the form's element or FormData must match the name of the parameter in the controller's action, e.g. &lt;input type="file" name="importFile"&gt;
     */
    public static postArticulateBlogmlImportFile<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlImportFileData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlImportFileResponses, PostArticulateBlogmlImportFileErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/import-file',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}

export class Posts {
    public static postArticulatePostsMarkdown<ThrowOnError extends boolean = false>(options?: Options<PostArticulatePostsMarkdownData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulatePostsMarkdownResponses, PostArticulatePostsMarkdownErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/posts/markdown',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}

export class Themes {
    /**
     * Gets the list of all available Articulate themes, both default and user-defined.
     * This endpoint returns the names of all available themes, including both default and user-defined themes.
     */
    public static getArticulateThemesAll<ThrowOnError extends boolean = false>(options?: Options<GetArticulateThemesAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateThemesAllResponses, GetArticulateThemesAllErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/themes/all',
            ...options
        });
    }
    
    /**
     * Copies an existing theme to a new theme with a specified name.
     * This endpoint creates a copy of an existing theme under a new name. The new theme name must be unique.
     */
    public static postArticulateThemesCopy<ThrowOnError extends boolean = false>(options?: Options<PostArticulateThemesCopyData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateThemesCopyResponses, PostArticulateThemesCopyErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/themes/copy',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Retrieves the list of available default Articulate themes.
     * This endpoint returns the names of default themes available for Articulate.
     */
    public static getArticulateThemesDefault<ThrowOnError extends boolean = false>(options?: Options<GetArticulateThemesDefaultData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateThemesDefaultResponses, GetArticulateThemesDefaultErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/themes/default',
            ...options
        });
    }
}