// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

/**
 * Represents the options for exporting blog data in BlogML format.
 */
export type ExportBlogMlModel = {
    /**
     * Gets or sets the unique identifier of the Articulate node to export.
     */
    articulateNodeId: string;
    /**
     * Gets or sets a value indicating whether images should be exported as Base64-encoded strings in the BlogML file.
     */
    exportImagesAsBase64: boolean;
};

/**
 * Represents the options for importing blog data from a BlogML file.
 */
export type ImportBlogMlModel = {
    /**
     * Gets or sets the unique identifier of the Articulate node to import into.
     */
    articulateNodeId: string;
    /**
     * Gets or sets a value indicating whether to overwrite existing posts during import.
     */
    overwrite: boolean;
    /**
     * Gets or sets the regular expression pattern to match in post content during import.
     */
    regexMatch?: string | null;
    /**
     * Gets or sets the replacement string for the regular expression match in post content.
     */
    regexReplace?: string | null;
    /**
     * Gets or sets a value indicating whether to publish imported posts.
     */
    publish: boolean;
    /**
     * Gets or sets the temporary file name of the uploaded BlogML file.
     */
    tempFile: string;
    /**
     * Gets or sets a value indicating whether to export Disqus XML after import.
     */
    exportDisqusXml: boolean;
    /**
     * Gets or sets a value indicating whether to import the first image found in each post.
     */
    importFirstImage: boolean;
};

/**
 * Represents the result of a BlogML import with operation statistics.
 */
export type ImportModel = {
    /**
     * Gets or sets the number of Posts that were imported.
     */
    postCount: number;
    /**
     * Gets or sets the number of Authors that were imported.
     */
    authorCount: number;
    /**
     * Gets or sets the number of comments that were written to the Disqus comments XML export file.
     */
    commentCount: number;
    /**
     * Gets or sets a value indicating whether the import completed successfully (true) or if it failed (false).
     */
    completed: boolean;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

/**
 * Represents the data required to copy an existing theme to a new theme name.
 */
export type PostCopyThemeModel = {
    /**
     * Gets or sets the name of the existing theme to copy.
     */
    themeName: string;
    /**
     * Gets or sets the new name for the copied theme.
     */
    newThemeName: string;
};

/**
 * Represents the response model for the BlogML post initialization.
 */
export type PostResponseModel = {
    /**
     * Gets or sets the temporary file name used for the uploaded BlogML file.
     */
    temporaryFileName?: string | null;
    /**
     * Gets or sets the number of posts detected in the BlogML file.
     */
    postCount: number;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type GetArticulateBlogArticulateGuidV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blog/articulate/guid';
};

export type GetArticulateBlogArticulateGuidV1Errors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The Articulate archive content type was not found.
     */
    404: unknown;
};

export type GetArticulateBlogArticulateGuidV1Responses = {
    /**
     * The Guid as a string, example: ce9e1f75-6428-46b1-8711-84829b9b3d1c
     */
    200: string;
};

export type GetArticulateBlogArticulateGuidV1Response = GetArticulateBlogArticulateGuidV1Responses[keyof GetArticulateBlogArticulateGuidV1Responses];

export type PostArticulateBlogExportV1Data = {
    /**
     * Represents the options for exporting blog data in BlogML format.
     */
    body?: ExportBlogMlModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blog/export';
};

export type PostArticulateBlogExportV1Errors = {
    /**
     * The chosen node is not an Articulate root node, or node does not exist, or Articulate is not installed correctly.
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Export failed due to a server error.
     */
    500: unknown;
};

export type PostArticulateBlogExportV1Responses = {
    /**
     * Returns the BlogML XML file as an octet-stream. The filename in the Content-Disposition header will be in the format: articulate-export-yyyyMMddHHmmss.xml.
     */
    200: string;
};

export type PostArticulateBlogExportV1Response = PostArticulateBlogExportV1Responses[keyof PostArticulateBlogExportV1Responses];

export type GetArticulateBlogExportDisqusV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blog/export/disqus';
};

export type GetArticulateBlogExportDisqusV1Errors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetArticulateBlogExportDisqusV1Responses = {
    /**
     * Returns the Disqus comment XML file as an octet-stream. The filename in the Content-Disposition header will be in the format: articulate-disqus-comments-yyyyMMddHHmmss.xml.
     */
    200: string;
};

export type GetArticulateBlogExportDisqusV1Response = GetArticulateBlogExportDisqusV1Responses[keyof GetArticulateBlogExportDisqusV1Responses];

export type PostArticulateBlogImportV1Data = {
    /**
     * Represents the options for importing blog data from a BlogML file.
     */
    body?: ImportBlogMlModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blog/import';
};

export type PostArticulateBlogImportV1Errors = {
    /**
     * The requested Articulate node ID could not be found or is not a valid Articulate node.
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The requested temporary file could not be found.
     */
    404: ProblemDetails;
    /**
     * Import failed due to a server error.
     */
    500: ProblemDetails;
};

export type PostArticulateBlogImportV1Error = PostArticulateBlogImportV1Errors[keyof PostArticulateBlogImportV1Errors];

export type PostArticulateBlogImportV1Responses = {
    /**
     * Represents the result of a BlogML import with operation statistics.
     */
    200: ImportModel;
};

export type PostArticulateBlogImportV1Response = PostArticulateBlogImportV1Responses[keyof PostArticulateBlogImportV1Responses];

export type PostArticulateBlogImportBeginV1Data = {
    body?: {
        /**
         * The file to import, must be an XML file in BlogML format.
         */
        importFile?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blog/import/begin';
};

export type PostArticulateBlogImportBeginV1Errors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The request was not a valid form file or the file was not XML.
     */
    415: unknown;
    /**
     * Upload failed due to a server error.
     */
    500: unknown;
};

export type PostArticulateBlogImportBeginV1Responses = {
    /**
     * Represents the response model for the BlogML post initialization.
     */
    200: PostResponseModel;
};

export type PostArticulateBlogImportBeginV1Response = PostArticulateBlogImportBeginV1Responses[keyof PostArticulateBlogImportBeginV1Responses];

export type GetArticulateEditorsThemesV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/editors/themes';
};

export type GetArticulateEditorsThemesV1Errors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetArticulateEditorsThemesV1Responses = {
    /**
     * Returns the list of all available theme names.
     */
    200: Array<string>;
};

export type GetArticulateEditorsThemesV1Response = GetArticulateEditorsThemesV1Responses[keyof GetArticulateEditorsThemesV1Responses];

export type PostArticulateThemesCopyV1Data = {
    /**
     * Represents the data required to copy an existing theme to a new theme name.
     */
    body?: PostCopyThemeModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/themes/copy';
};

export type PostArticulateThemesCopyV1Errors = {
    /**
     * The new theme name is already in use or the request is invalid.
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The source theme was not found.
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred while copying the theme.
     */
    500: ProblemDetails;
};

export type PostArticulateThemesCopyV1Error = PostArticulateThemesCopyV1Errors[keyof PostArticulateThemesCopyV1Errors];

export type PostArticulateThemesCopyV1Responses = {
    /**
     * Returns the name of the newly created theme.
     */
    200: string;
};

export type PostArticulateThemesCopyV1Response = PostArticulateThemesCopyV1Responses[keyof PostArticulateThemesCopyV1Responses];

export type GetArticulateThemesDefaultV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/themes/default';
};

export type GetArticulateThemesDefaultV1Errors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetArticulateThemesDefaultV1Responses = {
    /**
     * Returns the list of available default theme names.
     */
    200: Array<string>;
};

export type GetArticulateThemesDefaultV1Response = GetArticulateThemesDefaultV1Responses[keyof GetArticulateThemesDefaultV1Responses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44366' | (string & {});
};