// This file is auto-generated by @hey-api/openapi-ts

export type CreatePostResponse = {
    url?: string | null;
};

export type CsrfTokenResponse = {
    requestToken?: string | null;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type ExportModel = {
    articulateBlogNode: string;
    exportImagesAsBase64: boolean;
};

export type ImportFileResponse = {
    temporaryFileName: string;
    postCount: number;
};

export type ImportModel = {
    articulateBlogNode: string;
    overwrite: boolean;
    regexMatch?: string | null;
    regexReplace?: string | null;
    publish: boolean;
    tempFile: string;
    exportDisqusXml: boolean;
    importFirstImage: boolean;
};

export type ImportResponse = {
    postCount: number;
    authorCount: number;
    commentCount: number;
    completed: boolean;
};

export type LoginModel = {
    emailAddress: string;
    password: string;
};

export type LoginResponseBase = {
    [key: string]: never;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type StatusResponse = {
    isAuthenticated: boolean;
};

export type ThemeCopyModel = {
    themeName: string;
    newThemeName: string;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | {
        [key: string]: Array<string>;
    } | undefined;
};

export type GetAuthenticationCsrfTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/csrf-token';
};

export type GetAuthenticationCsrfTokenResponses = {
    /**
     * OK
     */
    200: CsrfTokenResponse;
};

export type GetAuthenticationCsrfTokenResponse = GetAuthenticationCsrfTokenResponses[keyof GetAuthenticationCsrfTokenResponses];

export type PostAuthenticationLoginData = {
    body?: LoginModel;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/login';
};

export type PostAuthenticationLoginErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Locked
     */
    423: ProblemDetails;
};

export type PostAuthenticationLoginError = PostAuthenticationLoginErrors[keyof PostAuthenticationLoginErrors];

export type PostAuthenticationLoginResponses = {
    /**
     * OK
     */
    200: LoginResponseBase;
};

export type PostAuthenticationLoginResponse = PostAuthenticationLoginResponses[keyof PostAuthenticationLoginResponses];

export type PostAuthenticationLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/logout';
};

export type PostAuthenticationLogoutErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostAuthenticationLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostAuthenticationLogoutResponse = PostAuthenticationLogoutResponses[keyof PostAuthenticationLogoutResponses];

export type GetAuthenticationStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/status';
};

export type GetAuthenticationStatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAuthenticationStatusResponses = {
    /**
     * OK
     */
    200: StatusResponse;
};

export type GetAuthenticationStatusResponse = GetAuthenticationStatusResponses[keyof GetAuthenticationStatusResponses];

export type PostArticulateBlogmlExportData = {
    body?: ExportModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/export';
};

export type PostArticulateBlogmlExportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type PostArticulateBlogmlExportError = PostArticulateBlogmlExportErrors[keyof PostArticulateBlogmlExportErrors];

export type PostArticulateBlogmlExportResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type PostArticulateBlogmlExportResponse = PostArticulateBlogmlExportResponses[keyof PostArticulateBlogmlExportResponses];

export type GetArticulateBlogmlExportDisqusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/export/disqus';
};

export type GetArticulateBlogmlExportDisqusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetArticulateBlogmlExportDisqusError = GetArticulateBlogmlExportDisqusErrors[keyof GetArticulateBlogmlExportDisqusErrors];

export type GetArticulateBlogmlExportDisqusResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetArticulateBlogmlExportDisqusResponse = GetArticulateBlogmlExportDisqusResponses[keyof GetArticulateBlogmlExportDisqusResponses];

export type PostArticulateBlogmlImportData = {
    body?: ImportModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/import';
};

export type PostArticulateBlogmlImportErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostArticulateBlogmlImportError = PostArticulateBlogmlImportErrors[keyof PostArticulateBlogmlImportErrors];

export type PostArticulateBlogmlImportResponses = {
    /**
     * OK
     */
    200: ImportResponse;
};

export type PostArticulateBlogmlImportResponse = PostArticulateBlogmlImportResponses[keyof PostArticulateBlogmlImportResponses];

export type PostArticulateBlogmlImportFileData = {
    body?: {
        importFile?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/import-file';
};

export type PostArticulateBlogmlImportFileErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Unsupported Media Type
     */
    415: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostArticulateBlogmlImportFileError = PostArticulateBlogmlImportFileErrors[keyof PostArticulateBlogmlImportFileErrors];

export type PostArticulateBlogmlImportFileResponses = {
    /**
     * OK
     */
    200: ImportFileResponse;
};

export type PostArticulateBlogmlImportFileResponse = PostArticulateBlogmlImportFileResponses[keyof PostArticulateBlogmlImportFileResponses];

export type PostArticulateEditorsMarkdownPostData = {
    body?: {
        json?: string;
        files?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/editors/markdown/post';
};

export type PostArticulateEditorsMarkdownPostErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ValidationProblemDetails;
};

export type PostArticulateEditorsMarkdownPostError = PostArticulateEditorsMarkdownPostErrors[keyof PostArticulateEditorsMarkdownPostErrors];

export type PostArticulateEditorsMarkdownPostResponses = {
    /**
     * OK
     */
    200: CreatePostResponse;
};

export type PostArticulateEditorsMarkdownPostResponse = PostArticulateEditorsMarkdownPostResponses[keyof PostArticulateEditorsMarkdownPostResponses];

export type PostArticulateThemeCopyData = {
    body?: ThemeCopyModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/theme/copy';
};

export type PostArticulateThemeCopyErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostArticulateThemeCopyError = PostArticulateThemeCopyErrors[keyof PostArticulateThemeCopyErrors];

export type PostArticulateThemeCopyResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostArticulateThemeCopyResponse = PostArticulateThemeCopyResponses[keyof PostArticulateThemeCopyResponses];

export type GetArticulateThemeDefaultData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/theme/default';
};

export type GetArticulateThemeDefaultErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetArticulateThemeDefaultError = GetArticulateThemeDefaultErrors[keyof GetArticulateThemeDefaultErrors];

export type GetArticulateThemeDefaultResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetArticulateThemeDefaultResponse = GetArticulateThemeDefaultResponses[keyof GetArticulateThemeDefaultResponses];

export type GetArticulateEditorsThemePickerThemesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/editors/theme-picker/themes';
};

export type GetArticulateEditorsThemePickerThemesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetArticulateEditorsThemePickerThemesError = GetArticulateEditorsThemePickerThemesErrors[keyof GetArticulateEditorsThemePickerThemesErrors];

export type GetArticulateEditorsThemePickerThemesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetArticulateEditorsThemePickerThemesResponse = GetArticulateEditorsThemePickerThemesResponses[keyof GetArticulateEditorsThemePickerThemesResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44366' | (string & {});
};