// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { PostArticulateBlogmlExportData, PostArticulateBlogmlExportResponses, PostArticulateBlogmlExportErrors, GetArticulateBlogmlExportDisqusData, GetArticulateBlogmlExportDisqusResponses, GetArticulateBlogmlExportDisqusErrors, PostArticulateBlogmlImportData, PostArticulateBlogmlImportResponses, PostArticulateBlogmlImportErrors, PostArticulateBlogmlImportFileData, PostArticulateBlogmlImportFileResponses, PostArticulateBlogmlImportFileErrors, PostArticulateEditorsMarkdownPostData, PostArticulateEditorsMarkdownPostResponses, PostArticulateEditorsMarkdownPostErrors, PostArticulateThemeCopyData, PostArticulateThemeCopyResponses, PostArticulateThemeCopyErrors, GetArticulateThemeDefaultData, GetArticulateThemeDefaultResponses, GetArticulateThemeDefaultErrors, GetArticulateEditorsThemePickerThemesData, GetArticulateEditorsThemePickerThemesResponses, GetArticulateEditorsThemePickerThemesErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BlogMl {
    /**
     * Exports blog data as a BlogML XML file.
     */
    public static postArticulateBlogmlExport<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlExportData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlExportResponses, PostArticulateBlogmlExportErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/export',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Downloads the exported Disqus comment XML file.
     */
    public static getArticulateBlogmlExportDisqus<ThrowOnError extends boolean = false>(options?: Options<GetArticulateBlogmlExportDisqusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateBlogmlExportDisqusResponses, GetArticulateBlogmlExportDisqusErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/export/disqus',
            ...options
        });
    }
    
    /**
     * Imports blog data from a previously uploaded BlogML XML file.
     */
    public static postArticulateBlogmlImport<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlImportData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlImportResponses, PostArticulateBlogmlImportErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/import',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Begins the BlogML import process by accepting an uploaded XML file.
     * The name specified in the form's element or FormData must match the name of the parameter, e.g., <input type="file" name="importFile">
     */
    public static postArticulateBlogmlImportFile<ThrowOnError extends boolean = false>(options?: Options<PostArticulateBlogmlImportFileData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateBlogmlImportFileResponses, PostArticulateBlogmlImportFileErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/blogml/import-file',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}

export class MarkdownEditor {
    public static postArticulateEditorsMarkdownPost<ThrowOnError extends boolean = false>(options?: Options<PostArticulateEditorsMarkdownPostData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateEditorsMarkdownPostResponses, PostArticulateEditorsMarkdownPostErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/editors/markdown/post',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}

export class ThemeOptions {
    public static postArticulateThemeCopy<ThrowOnError extends boolean = false>(options?: Options<PostArticulateThemeCopyData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostArticulateThemeCopyResponses, PostArticulateThemeCopyErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/theme/copy',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getArticulateThemeDefault<ThrowOnError extends boolean = false>(options?: Options<GetArticulateThemeDefaultData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateThemeDefaultResponses, GetArticulateThemeDefaultErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/theme/default',
            ...options
        });
    }
}

export class ThemePicker {
    /**
     * Gets the list of all available Articulate themes, both default and user-defined.
     * This endpoint returns the names of all available themes, including both default and user-defined themes.
     */
    public static getArticulateEditorsThemePickerThemes<ThrowOnError extends boolean = false>(options?: Options<GetArticulateEditorsThemePickerThemesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetArticulateEditorsThemePickerThemesResponses, GetArticulateEditorsThemePickerThemesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/articulate/editors/theme-picker/themes',
            ...options
        });
    }
}