// This file is auto-generated by @hey-api/openapi-ts

/**
 * Represents the response of creating a post.
 */
export type CreatePostResponse = {
    /**
     * The URL of the created post.
     */
    url: string;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

/**
 * Represents the options for exporting blog data in BlogML format.
 */
export type ExportModel = {
    /**
     * Gets or sets the unique identifier of the Articulate node to export.
     */
    articulateBlogNode: string;
    /**
     * Gets or sets a value indicating whether the images should be exported as Base64 strings within the BlogML XML file.
     */
    exportImagesAsBase64: boolean;
};

/**
 * Represents the response model for the BlogML post initialization.
 */
export type ImportFileResponse = {
    /**
     * Gets or sets the temporary file name used to store the uploaded BlogML file.
     */
    temporaryFileName: string;
    /**
     * Gets or sets the number of posts detected in the BlogML file.
     */
    postCount: number;
};

/**
 * Represents the options for importing blog data from a BlogML file.
 */
export type ImportModel = {
    /**
     * Gets or sets the unique identifier of the Articulate node to import into.
     */
    articulateBlogNode: string;
    /**
     * Gets or sets a value indicating whether to overwrite existing posts during import.
     */
    overwrite: boolean;
    /**
     * Gets or sets the regular expression pattern to match in post content during import.
     */
    regexMatch?: string | null;
    /**
     * Gets or sets the replacement string for the regular expression match in post content.
     */
    regexReplace?: string | null;
    /**
     * Gets or sets a value indicating whether to publish imported posts.
     */
    publish: boolean;
    /**
     * Gets or sets the temporary file name of the uploaded BlogML file.
     */
    tempFile: string;
    /**
     * Gets or sets a value indicating whether to export Disqus XML after import.
     */
    exportDisqusXml: boolean;
    /**
     * Gets or sets a value indicating whether to import the first image found in each post.
     */
    importFirstImage: boolean;
};

/**
 * Represents the result of a BlogML import with operation statistics.
 */
export type ImportResponse = {
    /**
     * Gets or sets the number of Posts that were imported.
     */
    postCount: number;
    /**
     * Gets or sets the number of Authors that were imported.
     */
    authorCount: number;
    /**
     * Gets or sets the number of comments that were written to the Disqus comments XML export file.
     */
    commentCount: number;
    /**
     * Gets or sets a value indicating whether the import completed successfully (true) or if it failed (false).
     */
    completed: boolean;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

/**
 * Represents the data required to copy an existing theme to a new theme name.
 * The new theme name must not contain any invalid file name characters.
 */
export type ThemeCopyModel = {
    /**
     * Gets or sets the name of the existing theme to copy.
     */
    themeName: string;
    /**
     * Gets or sets the new name for the copied theme.
     */
    newThemeName: string;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | {
        [key: string]: Array<string>;
    } | undefined;
};

export type PostArticulateBlogmlExportData = {
    /**
     * Represents the options for exporting blog data in BlogML format.
     */
    body?: ExportModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/export';
};

export type PostArticulateBlogmlExportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Export failed due to a server error.
     */
    500: ProblemDetails;
    /**
     * The service is unavailable or the blog node is invalid.
     */
    503: ProblemDetails;
};

export type PostArticulateBlogmlExportError = PostArticulateBlogmlExportErrors[keyof PostArticulateBlogmlExportErrors];

export type PostArticulateBlogmlExportResponses = {
    /**
     * Returns the BlogML XML file as a downloadable stream.
     */
    200: Blob | File;
};

export type PostArticulateBlogmlExportResponse = PostArticulateBlogmlExportResponses[keyof PostArticulateBlogmlExportResponses];

export type GetArticulateBlogmlExportDisqusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/export/disqus';
};

export type GetArticulateBlogmlExportDisqusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The Disqus XML export file could not be found.
     */
    404: ProblemDetails;
};

export type GetArticulateBlogmlExportDisqusError = GetArticulateBlogmlExportDisqusErrors[keyof GetArticulateBlogmlExportDisqusErrors];

export type GetArticulateBlogmlExportDisqusResponses = {
    /**
     * Returns the Disqus comment XML file as a downloadable stream.
     */
    200: Blob | File;
};

export type GetArticulateBlogmlExportDisqusResponse = GetArticulateBlogmlExportDisqusResponses[keyof GetArticulateBlogmlExportDisqusResponses];

export type PostArticulateBlogmlImportData = {
    /**
     * Represents the options for importing blog data from a BlogML file.
     */
    body?: ImportModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/import';
};

export type PostArticulateBlogmlImportErrors = {
    /**
     * The requested Articulate node ID could not be found or is not a valid Articulate node.
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The requested temporary file could not be found.
     */
    404: ProblemDetails;
    /**
     * Import failed due to a server error.
     */
    500: ProblemDetails;
};

export type PostArticulateBlogmlImportError = PostArticulateBlogmlImportErrors[keyof PostArticulateBlogmlImportErrors];

export type PostArticulateBlogmlImportResponses = {
    /**
     * Represents the result of a BlogML import with operation statistics.
     */
    200: ImportResponse;
};

export type PostArticulateBlogmlImportResponse = PostArticulateBlogmlImportResponses[keyof PostArticulateBlogmlImportResponses];

export type PostArticulateBlogmlImportFileData = {
    body?: {
        /**
         * The file to import, must be an XML file in BlogML format.
         */
        importFile?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/import-file';
};

export type PostArticulateBlogmlImportFileErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The request is not a valid form file, file is missing, or the file is not XML.
     */
    415: ProblemDetails;
    /**
     * Upload failed due to a server error.
     */
    500: ProblemDetails;
};

export type PostArticulateBlogmlImportFileError = PostArticulateBlogmlImportFileErrors[keyof PostArticulateBlogmlImportFileErrors];

export type PostArticulateBlogmlImportFileResponses = {
    /**
     * Represents the response model for the BlogML post initialization.
     */
    200: ImportFileResponse;
};

export type PostArticulateBlogmlImportFileResponse = PostArticulateBlogmlImportFileResponses[keyof PostArticulateBlogmlImportFileResponses];

export type PostArticulateEditorsMarkdownPostData = {
    body?: {
        /**
         * The JSON model containing the post data: Title, Body, Slug, Excerpt, Tags, Categories, ArticulateBlogNode, and whether the first image should be extracted as a dedicated property.
         */
        json?: string;
        /**
         * Any uploaded images as part of the multipart/form-data request.
         */
        files?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/editors/markdown/post';
};

export type PostArticulateEditorsMarkdownPostErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ValidationProblemDetails;
};

export type PostArticulateEditorsMarkdownPostError = PostArticulateEditorsMarkdownPostErrors[keyof PostArticulateEditorsMarkdownPostErrors];

export type PostArticulateEditorsMarkdownPostResponses = {
    /**
     * Represents the response of creating a post.
     */
    200: CreatePostResponse;
};

export type PostArticulateEditorsMarkdownPostResponse = PostArticulateEditorsMarkdownPostResponses[keyof PostArticulateEditorsMarkdownPostResponses];

export type PostArticulateThemeCopyData = {
    /**
     * Represents the data required to copy an existing theme to a new theme name.
     * The new theme name must not contain any invalid file name characters.
     */
    body?: ThemeCopyModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/theme/copy';
};

export type PostArticulateThemeCopyErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The theme name specified in the model does not exist.
     */
    404: ProblemDetails;
    /**
     * The new theme name specified in the model already exists.
     */
    409: ProblemDetails;
    /**
     * An unexpected error occurred during the theme copy operation.
     */
    500: ProblemDetails;
};

export type PostArticulateThemeCopyError = PostArticulateThemeCopyErrors[keyof PostArticulateThemeCopyErrors];

export type PostArticulateThemeCopyResponses = {
    /**
     * The theme was successfully copied to the new theme name.
     */
    200: string;
};

export type PostArticulateThemeCopyResponse = PostArticulateThemeCopyResponses[keyof PostArticulateThemeCopyResponses];

export type GetArticulateThemeDefaultData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/theme/default';
};

export type GetArticulateThemeDefaultErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * An unexpected error occurred while retrieving default themes.
     */
    500: ProblemDetails;
};

export type GetArticulateThemeDefaultError = GetArticulateThemeDefaultErrors[keyof GetArticulateThemeDefaultErrors];

export type GetArticulateThemeDefaultResponses = {
    /**
     * Returns the list of default theme names.
     */
    200: Array<string>;
};

export type GetArticulateThemeDefaultResponse = GetArticulateThemeDefaultResponses[keyof GetArticulateThemeDefaultResponses];

export type GetArticulateEditorsThemePickerThemesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/editors/theme-picker/themes';
};

export type GetArticulateEditorsThemePickerThemesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetArticulateEditorsThemePickerThemesError = GetArticulateEditorsThemePickerThemesErrors[keyof GetArticulateEditorsThemePickerThemesErrors];

export type GetArticulateEditorsThemePickerThemesResponses = {
    /**
     * Returns the list of all available theme names.
     */
    200: Array<string>;
};

export type GetArticulateEditorsThemePickerThemesResponse = GetArticulateEditorsThemePickerThemesResponses[keyof GetArticulateEditorsThemePickerThemesResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44366' | (string & {});
};