// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

/**
 * Represents the options for exporting blog data in BlogML format.
 */
export type ExportModel = {
    /**
     * Gets or sets the unique identifier of the Articulate node to export.
     */
    articulateBlogNode: string;
    /**
     * Gets or sets a value indicating whether images should be exported as Base64-encoded strings in the BlogML file.
     */
    exportImagesAsBase64: boolean;
};

/**
 * Represents the response model for the BlogML post initialization.
 */
export type ImportFileResponse = {
    /**
     * Gets or sets the temporary file name used for the uploaded BlogML file.
     */
    temporaryFileName: string;
    /**
     * Gets or sets the number of posts detected in the BlogML file.
     */
    postCount: number;
};

/**
 * Represents the options for importing blog data from a BlogML file.
 */
export type ImportModel = {
    /**
     * Gets or sets the unique identifier of the Articulate node to import into.
     */
    articulateBlogNode: string;
    /**
     * Gets or sets a value indicating whether to overwrite existing posts during import.
     */
    overwrite: boolean;
    /**
     * Gets or sets the regular expression pattern to match in post content during import.
     */
    regexMatch?: string | null;
    /**
     * Gets or sets the replacement string for the regular expression match in post content.
     */
    regexReplace?: string | null;
    /**
     * Gets or sets a value indicating whether to publish imported posts.
     */
    publish: boolean;
    /**
     * Gets or sets the temporary file name of the uploaded BlogML file.
     */
    tempFile: string;
    /**
     * Gets or sets a value indicating whether to export Disqus XML after import.
     */
    exportDisqusXml: boolean;
    /**
     * Gets or sets a value indicating whether to import the first image found in each post.
     */
    importFirstImage: boolean;
};

/**
 * Represents the result of a BlogML import with operation statistics.
 */
export type ImportResponse = {
    /**
     * Gets or sets the number of Posts that were imported.
     */
    postCount: number;
    /**
     * Gets or sets the number of Authors that were imported.
     */
    authorCount: number;
    /**
     * Gets or sets the number of comments that were written to the Disqus comments XML export file.
     */
    commentCount: number;
    /**
     * Gets or sets a value indicating whether the import completed successfully (true) or if it failed (false).
     */
    completed: boolean;
};

/**
 * Represents the login model for authentication.
 */
export type LoginModel = {
    /**
     * Gets the email address of the user.
     */
    readonly emailAddress: string;
    /**
     * Gets the password of the user.
     */
    readonly password: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

/**
 * Represents the authentication status response.
 */
export type StatusResponse = {
    /**
     * Gets a value indicating whether the user is authenticated.
     */
    isAuthenticated: boolean;
};

/**
 * Represents the data required to copy an existing theme to a new theme name.
 */
export type ThemeCopyModel = {
    /**
     * Gets or sets the name of the existing theme to copy.
     */
    themeName: string;
    /**
     * Gets or sets the new name for the copied theme.
     */
    newThemeName: string;
};

/**
 * Represents the response when two-factor authentication is required.
 */
export type TwoFactorRequiredResponse = {
    /**
     * Gets a value indicating whether two-factor authentication is required.
     */
    requiresTwoFactor: boolean;
    /**
     * Gets the URL to redirect the user for two-factor authentication.
     */
    redirectUrl?: string | null;
};

export type PostAuthenticationLoginData = {
    /**
     * Represents the login model for authentication.
     */
    body?: LoginModel;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/login';
};

export type PostAuthenticationLoginErrors = {
    /**
     * Email and password are required.
     */
    400: unknown;
    /**
     * Authentication failed.
     */
    401: unknown;
    /**
     * User login is disabled.
     */
    403: unknown;
    /**
     * User is locked out.
     */
    423: unknown;
};

export type PostAuthenticationLoginResponses = {
    /**
     * Represents the response when two-factor authentication is required.
     */
    200: TwoFactorRequiredResponse;
};

export type PostAuthenticationLoginResponse = PostAuthenticationLoginResponses[keyof PostAuthenticationLoginResponses];

export type PostAuthenticationLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/logout';
};

export type PostAuthenticationLogoutErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostAuthenticationLogoutResponses = {
    /**
     * Logout successful.
     */
    200: unknown;
};

export type GetAuthenticationStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articulate/management/api/v1/authentication/status';
};

export type GetAuthenticationStatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAuthenticationStatusResponses = {
    /**
     * Represents the authentication status response.
     */
    200: StatusResponse;
};

export type GetAuthenticationStatusResponse = GetAuthenticationStatusResponses[keyof GetAuthenticationStatusResponses];

export type PostArticulateBlogmlExportData = {
    /**
     * Represents the options for exporting blog data in BlogML format.
     */
    body?: ExportModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/export';
};

export type PostArticulateBlogmlExportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Export failed due to a server error.
     */
    500: unknown;
    /**
     * Service Unavailable
     */
    503: unknown;
};

export type PostArticulateBlogmlExportResponses = {
    /**
     * Returns the BlogML XML file as an octet-stream. The filename in the Content-Disposition header will be in the format: articulate-export-yyyyMMddHHmmss.xml.
     */
    200: string;
};

export type PostArticulateBlogmlExportResponse = PostArticulateBlogmlExportResponses[keyof PostArticulateBlogmlExportResponses];

export type GetArticulateBlogmlExportDisqusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/export/disqus';
};

export type GetArticulateBlogmlExportDisqusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The Disqus XML export file could not be found.
     */
    404: unknown;
};

export type GetArticulateBlogmlExportDisqusResponses = {
    /**
     * Returns the Disqus comment XML file as an octet-stream. The filename in the Content-Disposition header will be in the format: articulate-disqus-comments-yyyyMMddHHmmss.xml.
     */
    200: string;
};

export type GetArticulateBlogmlExportDisqusResponse = GetArticulateBlogmlExportDisqusResponses[keyof GetArticulateBlogmlExportDisqusResponses];

export type PostArticulateBlogmlImportData = {
    /**
     * Represents the options for importing blog data from a BlogML file.
     */
    body?: ImportModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/import';
};

export type PostArticulateBlogmlImportErrors = {
    /**
     * The requested Articulate node ID could not be found or is not a valid Articulate node.
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The requested temporary file could not be found.
     */
    404: unknown;
    /**
     * Import failed due to a server error.
     */
    500: unknown;
};

export type PostArticulateBlogmlImportResponses = {
    /**
     * Represents the result of a BlogML import with operation statistics.
     */
    200: ImportResponse;
};

export type PostArticulateBlogmlImportResponse = PostArticulateBlogmlImportResponses[keyof PostArticulateBlogmlImportResponses];

export type PostArticulateBlogmlImportFileData = {
    body?: {
        /**
         * The file to import, must be an XML file in BlogML format.
         */
        importFile?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/blogml/import-file';
};

export type PostArticulateBlogmlImportFileErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The request is not a valid form file, file is missing or the file is not XML.
     */
    415: unknown;
    /**
     * Upload failed due to a server error.
     */
    500: unknown;
};

export type PostArticulateBlogmlImportFileResponses = {
    /**
     * Represents the response model for the BlogML post initialization.
     */
    200: ImportFileResponse;
};

export type PostArticulateBlogmlImportFileResponse = PostArticulateBlogmlImportFileResponses[keyof PostArticulateBlogmlImportFileResponses];

export type PostArticulateEditorsMarkdownPostData = {
    body?: {
        json?: string;
        files?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/editors/markdown/post';
};

export type PostArticulateEditorsMarkdownPostErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostArticulateEditorsMarkdownPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetArticulateEditorsThemePickerThemesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/editors/theme-picker/themes';
};

export type GetArticulateEditorsThemePickerThemesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetArticulateEditorsThemePickerThemesResponses = {
    /**
     * Returns the list of all available theme names.
     */
    200: Array<string>;
};

export type GetArticulateEditorsThemePickerThemesResponse = GetArticulateEditorsThemePickerThemesResponses[keyof GetArticulateEditorsThemePickerThemesResponses];

export type PostArticulateThemesCopyData = {
    /**
     * Represents the data required to copy an existing theme to a new theme name.
     */
    body?: ThemeCopyModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/themes/copy';
};

export type PostArticulateThemesCopyErrors = {
    /**
     * The new theme name is already in use or the request is invalid.
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The source theme was not found.
     */
    404: unknown;
    /**
     * An internal server error occurred while copying the theme.
     */
    500: unknown;
};

export type PostArticulateThemesCopyResponses = {
    /**
     * Returns the name of the newly created theme.
     */
    200: string;
};

export type PostArticulateThemesCopyResponse = PostArticulateThemesCopyResponses[keyof PostArticulateThemesCopyResponses];

export type GetArticulateThemesDefaultData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/articulate/themes/default';
};

export type GetArticulateThemesDefaultErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetArticulateThemesDefaultResponses = {
    /**
     * Returns the list of available default theme names.
     */
    200: Array<string>;
};

export type GetArticulateThemesDefaultResponse = GetArticulateThemesDefaultResponses[keyof GetArticulateThemesDefaultResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44366' | (string & {});
};